blank_issues_enabled: true
contact_links:
  - name: Dokumentacja repozytorium
    url: https://github.com/kpietrzyk/qa_knowladge_base/blob/main/README.md
    about: Zapoznaj się z README przed otwarciem Issue
